### ISSUE TITLE
Baseline TouchUps

### ISSUE THREAD

**Issue by solbarth** [zoesol/furry-telegram#19]
- [x] Put a grey background around the view that hold all the habit icons.
- [x] Make the log habit Diaglog input a full dialog box and not just a one line input. 
- [x] Add Cancel Buttons to the Add Habit and Add New Goal Pages for users that decide that no longer want to create new habits or goals. 
- [x] Add undo functionality to habit icons so when clicked a second time the icons return to green background and the most recent log in the history for that habit is removed.

**Comment by zoesol** [comment]
@solbarth there are already back buttons that essentially do the cancelling so I'm thinking explicit buttons aren't necessary?

**Comment by zoesol** [comment]
Undo functionality on home page no longer a part of app design. Closing issue
